sudo: required
dist: trusty
language: c

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        postgresql: "10"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10
      

before_script:
  - createdb hll_regress                                     # Create the test database
script:
  - make && sudo make install
  - psql -c "create extension hll" hll_regress
  - make -C regress
