sudo: required
dist: trusty
language: c

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        postgresql: "10"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10

before_script:
  - sudo apt-get install postgresql-server-dev-all
  - sudo apt-get install postgresql-common
  
script:
  - make && sudo make install
  - psql -U postgres -c "create extension hll" travis
  - make -C regress
