sudo: required
dist: trusty
language: c

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        postgresql: "10"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10
      
script:
  - make && sudo make install
  - psql -O travis -p 5433 -c "create extension hll" travis
  - make -C regress
